// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * ApprovalRequest
 *
 * The HITL spine — every human gate in any workflow passes through one of these.
 */
export type ApprovalRequest = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Decided At
     */
    decided_at?: string | null;
    /**
     * Decided By
     */
    decided_by?: string | null;
    /**
     * Graph Thread Id
     */
    graph_thread_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    status?: ApprovalStatus;
    /**
     * Tenant Id
     */
    tenant_id?: string;
    /**
     * Workflow
     */
    workflow: string;
};

/**
 * ApprovalStatus
 */
export const ApprovalStatus = {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected'
} as const;

/**
 * ApprovalStatus
 */
export type ApprovalStatus = typeof ApprovalStatus[keyof typeof ApprovalStatus];

/**
 * AttachDocument
 */
export type AttachDocument = {
    /**
     * File Id
     */
    file_id: string;
    kind?: DocumentKind;
    /**
     * Milestone Id
     */
    milestone_id?: string | null;
    /**
     * Title
     */
    title?: string;
};

/**
 * CallRecord
 *
 * A voice call, raw and extracted layers kept separate.
 */
export type CallRecord = {
    /**
     * Contact Id
     */
    contact_id?: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Extracted
     */
    extracted?: {
        [key: string]: unknown;
    };
    /**
     * Listing Key
     */
    listing_key?: string;
    /**
     * Outcome
     */
    outcome?: string;
    /**
     * Tenant Id
     */
    tenant_id?: string;
    /**
     * Transcript
     */
    transcript?: string;
    /**
     * Vapi Call Id
     */
    vapi_call_id: string;
};

/**
 * Contact
 *
 * CRM contact DTO. The CRM behind `CRMPort` is the source of truth —
 * this is a read-through shape, never persisted on our side.
 *
 * `crm_id` is the contact's id in whichever CRM this deploy is wired to
 * (a FollowUpBoss person id, a Sierra Interactive lead id, …); it is only
 * meaningful to the adapter that produced it.
 */
export type Contact = {
    /**
     * Crm Id
     */
    crm_id: string;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Phone
     */
    phone?: string | null;
    /**
     * Role
     */
    role?: string;
};

/**
 * DecideRequest
 *
 * Wire shape for a decision. `decided_by` is intentionally absent — the API
 * stamps it from the authenticated principal, never the client.
 *
 * `edited_payload` stays a dict here because its shape depends on the approval
 * *kind*, known only after the row is fetched; the decide route validates it
 * against the kind's boundary model (EditedMessagePayload for the
 * outbound-message gate) before anything reaches an engine.
 */
export type DecideRequest = {
    decision: ApprovalStatus;
    /**
     * Edited Payload
     */
    edited_payload?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DecisionResponse
 */
export type DecisionResponse = {
    approval: ApprovalRequest;
    workflow: WorkflowRunResult;
};

/**
 * Document
 */
export type Document = {
    /**
     * Created At
     */
    created_at: string;
    file: FileRef;
    /**
     * Id
     */
    id: string;
    kind?: DocumentKind;
    /**
     * Milestone Id
     */
    milestone_id?: string | null;
    /**
     * Tenant Id
     */
    tenant_id?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Transaction Id
     */
    transaction_id: string;
    /**
     * Uploaded By
     */
    uploaded_by?: string;
};

/**
 * DocumentKind
 */
export const DocumentKind = {
    PURCHASE_AGREEMENT: 'purchase_agreement',
    DISCLOSURES: 'disclosures',
    INSPECTION_REPORT: 'inspection_report',
    APPRAISAL_REPORT: 'appraisal_report',
    LOAN_APPROVAL: 'loan_approval',
    CLOSING_STATEMENT: 'closing_statement',
    OTHER: 'other'
} as const;

/**
 * DocumentKind
 */
export type DocumentKind = typeof DocumentKind[keyof typeof DocumentKind];

/**
 * FeedbackSource
 */
export const FeedbackSource = { CALL: 'call', FORM: 'form' } as const;

/**
 * FeedbackSource
 */
export type FeedbackSource = typeof FeedbackSource[keyof typeof FeedbackSource];

/**
 * FileRef
 *
 * A pointer to a file living in the office file store.
 *
 * `file_id` is the backend's opaque identifier; `web_url` is where a human
 * opens the file (the provider's own viewer). No provider-specific fields.
 */
export type FileRef = {
    /**
     * File Id
     */
    file_id: string;
    /**
     * Mime Type
     */
    mime_type?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Size Bytes
     */
    size_bytes?: number | null;
    /**
     * Web Url
     */
    web_url?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Listing
 */
export type Listing = {
    /**
     * Address
     */
    address?: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Agent Name
     */
    agent_name: string;
    /**
     * Bathrooms
     */
    bathrooms?: number | null;
    /**
     * Bedrooms
     */
    bedrooms?: number | null;
    /**
     * City
     */
    city?: string;
    /**
     * List Price
     *
     * List price in whole dollars
     */
    list_price?: number | null;
    /**
     * Living Area Sqft
     */
    living_area_sqft?: number | null;
    /**
     * Media
     */
    media?: Array<ListingMedia>;
    /**
     * Mls Id
     */
    mls_id: string;
    /**
     * Modified At
     */
    modified_at: string;
    /**
     * Postal Code
     */
    postal_code: string;
    /**
     * Remarks
     */
    remarks?: string;
    /**
     * State
     */
    state: string;
    status: ListingStatus;
    /**
     * Year Built
     */
    year_built?: number | null;
};

/**
 * ListingMedia
 */
export type ListingMedia = {
    /**
     * Description
     */
    description?: string;
    /**
     * Listing Key
     */
    listing_key: string;
    /**
     * Media Key
     */
    media_key: string;
    /**
     * Order
     */
    order?: number;
    /**
     * Url
     */
    url: string;
};

/**
 * ListingStatus
 */
export const ListingStatus = {
    ACTIVE: 'active',
    PENDING: 'pending',
    CLOSED: 'closed'
} as const;

/**
 * ListingStatus
 */
export type ListingStatus = typeof ListingStatus[keyof typeof ListingStatus];

/**
 * MagicRedeem
 */
export type MagicRedeem = {
    /**
     * Token
     */
    token: string;
};

/**
 * MagicRequest
 */
export type MagicRequest = {
    /**
     * Email
     */
    email: string;
};

/**
 * Message
 *
 * One outbound business communication to a person.
 *
 * `extra="forbid"`: this model is the single source of truth for the comms-history
 * shape — a field that isn't declared here doesn't exist.
 */
export type Message = {
    /**
     * Body
     */
    body?: string;
    channel?: MessageChannel;
    /**
     * Contact Id
     */
    contact_id?: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Listing Key
     */
    listing_key?: string;
    /**
     * Provider Message Id
     */
    provider_message_id?: string;
    /**
     * Recipient
     */
    recipient: string;
    /**
     * Sent At
     */
    sent_at?: string | null;
    status?: MessageStatus;
    /**
     * Subject
     */
    subject?: string;
    /**
     * Template Ref
     */
    template_ref?: string;
    /**
     * Tenant Id
     */
    tenant_id?: string;
    /**
     * Transaction Id
     */
    transaction_id?: string;
};

/**
 * MessageChannel
 */
export const MessageChannel = { EMAIL: 'email', SMS: 'sms' } as const;

/**
 * MessageChannel
 */
export type MessageChannel = typeof MessageChannel[keyof typeof MessageChannel];

/**
 * MessageStatus
 *
 * Lifecycle of an outbound message.
 *
 * DRAFTED → SENT | FAILED is the direct-send path (BOP-015). Workflow-drafted
 * comms (BOP-019) insert a human gate between draft and send:
 * PENDING_APPROVAL → SENT | FAILED | REJECTED — no drafted text leaves the
 * boundary without a human decision. DELIVERED is set only by a provider
 * delivery-status webhook (BOP-018): SENT means the provider accepted the
 * message; DELIVERED means the provider confirmed the handset got it. A
 * delivery callback can also move SENT → FAILED.
 */
export const MessageStatus = {
    DRAFTED: 'drafted',
    PENDING_APPROVAL: 'pending_approval',
    SENT: 'sent',
    DELIVERED: 'delivered',
    FAILED: 'failed',
    REJECTED: 'rejected'
} as const;

/**
 * MessageStatus
 *
 * Lifecycle of an outbound message.
 *
 * DRAFTED → SENT | FAILED is the direct-send path (BOP-015). Workflow-drafted
 * comms (BOP-019) insert a human gate between draft and send:
 * PENDING_APPROVAL → SENT | FAILED | REJECTED — no drafted text leaves the
 * boundary without a human decision. DELIVERED is set only by a provider
 * delivery-status webhook (BOP-018): SENT means the provider accepted the
 * message; DELIVERED means the provider confirmed the handset got it. A
 * delivery callback can also move SENT → FAILED.
 */
export type MessageStatus = typeof MessageStatus[keyof typeof MessageStatus];

/**
 * MilestoneStatus
 */
export const MilestoneStatus = {
    PENDING: 'pending',
    COMPLETE: 'complete',
    WAIVED: 'waived'
} as const;

/**
 * MilestoneStatus
 */
export type MilestoneStatus = typeof MilestoneStatus[keyof typeof MilestoneStatus];

/**
 * MilestoneType
 */
export const MilestoneType = {
    INSPECTION: 'inspection',
    APPRAISAL: 'appraisal',
    FINANCING: 'financing',
    CLOSING: 'closing',
    CUSTOM: 'custom'
} as const;

/**
 * MilestoneType
 */
export type MilestoneType = typeof MilestoneType[keyof typeof MilestoneType];

/**
 * MilestoneView
 */
export type MilestoneView = {
    /**
     * Blocked Reason
     */
    blocked_reason?: string | null;
    /**
     * Classification
     */
    classification: string;
    /**
     * Days Until Due
     */
    days_until_due: number;
    /**
     * Document Satisfied
     */
    document_satisfied?: boolean | null;
    /**
     * Due Date
     */
    due_date: string;
    /**
     * Escalation Level
     */
    escalation_level?: number;
    expected_document?: DocumentKind | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner
     */
    owner?: string;
    status?: MilestoneStatus;
    /**
     * Tenant Id
     */
    tenant_id?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Transaction Id
     */
    transaction_id: string;
    type: MilestoneType;
};

/**
 * MutationOutcome
 */
export const MutationOutcome = { SUCCESS: 'success', FAILURE: 'failure' } as const;

/**
 * MutationOutcome
 */
export type MutationOutcome = typeof MutationOutcome[keyof typeof MutationOutcome];

/**
 * MutationRecord
 *
 * One durable, reviewable line in the business audit trail: a single write the
 * system performed against an external system across the MCP boundary.
 *
 * Distinct from an ApprovalRequest (which records a *decision*) and from tracing
 * (which records *execution* for debugging) — this is the trustworthy history of
 * the actions themselves: what tool ran, on which integration, with what
 * (secret-redacted) arguments, under which workflow run, on whose authority, and
 * with what result. Both success and failure are recorded.
 */
export type MutationRecord = {
    /**
     * Actor
     */
    actor?: string | null;
    /**
     * Approval Id
     */
    approval_id?: string | null;
    /**
     * Args
     */
    args: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error
     */
    error?: string | null;
    /**
     * External Id
     */
    external_id?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Integration
     */
    integration: string;
    outcome: MutationOutcome;
    /**
     * Tool
     */
    tool: string;
    /**
     * Workflow
     */
    workflow: string;
    /**
     * Workflow Run Id
     */
    workflow_run_id: string;
};

/**
 * OpenTransaction
 */
export type OpenTransaction = {
    /**
     * Close Date
     */
    close_date?: string | null;
    /**
     * Contract Date
     */
    contract_date: string;
    /**
     * Listing Key
     */
    listing_key: string;
    /**
     * Parties
     */
    parties?: Array<TransactionParty>;
};

/**
 * OutboundCallRequest
 */
export type OutboundCallRequest = {
    /**
     * Contact Id
     */
    contact_id: string;
    /**
     * Listing Key
     */
    listing_key: string;
    /**
     * Scenario
     */
    scenario?: string | null;
};

/**
 * OutboundCallResult
 */
export type OutboundCallResult = {
    /**
     * Call Id
     */
    call_id: string;
    /**
     * Status
     */
    status?: string;
};

/**
 * RefreshRequest
 */
export type RefreshRequest = {
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * RefreshResponse
 */
export type RefreshResponse = {
    /**
     * Session Token
     */
    session_token: string;
};

/**
 * SeedRequest
 */
export type SeedRequest = {
    /**
     * Reset
     */
    reset?: boolean;
};

/**
 * SeedResult
 */
export type SeedResult = {
    /**
     * Milestones
     */
    milestones: number;
    /**
     * Seeded
     */
    seeded: boolean;
    /**
     * Transactions
     */
    transactions: number;
};

/**
 * SendMessageRequest
 */
export type SendMessageRequest = {
    channel?: MessageChannel;
    /**
     * Contact Id
     */
    contact_id?: string;
    /**
     * Listing Key
     */
    listing_key?: string;
    /**
     * Params
     */
    params?: {
        [key: string]: string;
    };
    /**
     * Recipient
     */
    recipient: string;
    /**
     * Request Id
     */
    request_id?: string;
    /**
     * Template
     */
    template: string;
    /**
     * Transaction Id
     */
    transaction_id?: string;
};

/**
 * Sentiment
 */
export const Sentiment = {
    POSITIVE: 'positive',
    NEUTRAL: 'neutral',
    NEGATIVE: 'negative'
} as const;

/**
 * Sentiment
 */
export type Sentiment = typeof Sentiment[keyof typeof Sentiment];

/**
 * SessionResponse
 */
export type SessionResponse = {
    /**
     * Refresh Token
     */
    refresh_token: string;
    /**
     * Session Token
     */
    session_token: string;
};

/**
 * ShowingFeedback
 */
export type ShowingFeedback = {
    /**
     * Call Id
     */
    call_id?: string | null;
    /**
     * Contact Id
     */
    contact_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Listing Key
     */
    listing_key: string;
    sentiment?: Sentiment;
    source?: FeedbackSource;
    /**
     * Structured Answers
     */
    structured_answers?: {
        [key: string]: unknown;
    };
    /**
     * Tenant Id
     */
    tenant_id?: string;
};

/**
 * StartListingToContract
 */
export type StartListingToContract = {
    /**
     * Listing Key
     */
    listing_key: string;
};

/**
 * Transaction
 */
export type Transaction = {
    /**
     * Close Date
     */
    close_date?: string | null;
    /**
     * Contract Date
     */
    contract_date: string;
    /**
     * Id
     */
    id: string;
    /**
     * Listing Key
     */
    listing_key: string;
    /**
     * Parties
     */
    parties?: Array<TransactionParty>;
    stage: TransactionStage;
    /**
     * Tenant Id
     */
    tenant_id?: string;
};

/**
 * TransactionDetail
 */
export type TransactionDetail = {
    /**
     * Documents
     */
    documents: Array<Document>;
    /**
     * Milestones
     */
    milestones: Array<MilestoneView>;
    transaction: Transaction;
};

/**
 * TransactionParty
 */
export type TransactionParty = {
    /**
     * Contact Id
     */
    contact_id?: string | null;
    /**
     * Email
     */
    email?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Role
     */
    role: string;
};

/**
 * TransactionStage
 */
export const TransactionStage = {
    UNDER_CONTRACT: 'under_contract',
    CONTINGENCIES: 'contingencies',
    CLEAR_TO_CLOSE: 'clear_to_close',
    CLOSED: 'closed',
    CANCELLED: 'cancelled'
} as const;

/**
 * TransactionStage
 */
export type TransactionStage = typeof TransactionStage[keyof typeof TransactionStage];

/**
 * UploadDocument
 */
export type UploadDocument = {
    /**
     * Content Text
     */
    content_text: string;
    /**
     * Folder
     */
    folder?: string;
    kind?: DocumentKind;
    /**
     * Milestone Id
     */
    milestone_id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Title
     */
    title?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkflowRunResult
 */
export type WorkflowRunResult = {
    approval?: ApprovalRequest | null;
    /**
     * Output
     */
    output?: {
        [key: string]: unknown;
    } | null;
    /**
     * Status
     */
    status: string;
    /**
     * Thread Id
     */
    thread_id: string;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Response Root  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type RootGetResponse = RootGetResponses[keyof RootGetResponses];

export type ListApprovalsApprovalsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: ApprovalStatus | null;
    };
    url: '/approvals';
};

export type ListApprovalsApprovalsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListApprovalsApprovalsGetError = ListApprovalsApprovalsGetErrors[keyof ListApprovalsApprovalsGetErrors];

export type ListApprovalsApprovalsGetResponses = {
    /**
     * Response List Approvals Approvals Get
     *
     * Successful Response
     */
    200: Array<ApprovalRequest>;
};

export type ListApprovalsApprovalsGetResponse = ListApprovalsApprovalsGetResponses[keyof ListApprovalsApprovalsGetResponses];

export type GetApprovalApprovalsApprovalIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/approvals/{approval_id}';
};

export type GetApprovalApprovalsApprovalIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApprovalApprovalsApprovalIdGetError = GetApprovalApprovalsApprovalIdGetErrors[keyof GetApprovalApprovalsApprovalIdGetErrors];

export type GetApprovalApprovalsApprovalIdGetResponses = {
    /**
     * Successful Response
     */
    200: ApprovalRequest;
};

export type GetApprovalApprovalsApprovalIdGetResponse = GetApprovalApprovalsApprovalIdGetResponses[keyof GetApprovalApprovalsApprovalIdGetResponses];

export type DecideApprovalApprovalsApprovalIdDecidePostData = {
    body: DecideRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/approvals/{approval_id}/decide';
};

export type DecideApprovalApprovalsApprovalIdDecidePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DecideApprovalApprovalsApprovalIdDecidePostError = DecideApprovalApprovalsApprovalIdDecidePostErrors[keyof DecideApprovalApprovalsApprovalIdDecidePostErrors];

export type DecideApprovalApprovalsApprovalIdDecidePostResponses = {
    /**
     * Successful Response
     */
    200: DecisionResponse;
};

export type DecideApprovalApprovalsApprovalIdDecidePostResponse = DecideApprovalApprovalsApprovalIdDecidePostResponses[keyof DecideApprovalApprovalsApprovalIdDecidePostResponses];

export type ListMutationsAuditGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Workflow Run Id
         */
        workflow_run_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/audit';
};

export type ListMutationsAuditGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMutationsAuditGetError = ListMutationsAuditGetErrors[keyof ListMutationsAuditGetErrors];

export type ListMutationsAuditGetResponses = {
    /**
     * Response List Mutations Audit Get
     *
     * Successful Response
     */
    200: Array<MutationRecord>;
};

export type ListMutationsAuditGetResponse = ListMutationsAuditGetResponses[keyof ListMutationsAuditGetResponses];

export type AuthConfigAuthConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/config';
};

export type AuthConfigAuthConfigGetResponses = {
    /**
     * Response Auth Config Auth Config Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AuthConfigAuthConfigGetResponse = AuthConfigAuthConfigGetResponses[keyof AuthConfigAuthConfigGetResponses];

export type RedeemMagicLinkAuthMagicRedeemPostData = {
    body: MagicRedeem;
    path?: never;
    query?: never;
    url: '/auth/magic/redeem';
};

export type RedeemMagicLinkAuthMagicRedeemPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RedeemMagicLinkAuthMagicRedeemPostError = RedeemMagicLinkAuthMagicRedeemPostErrors[keyof RedeemMagicLinkAuthMagicRedeemPostErrors];

export type RedeemMagicLinkAuthMagicRedeemPostResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type RedeemMagicLinkAuthMagicRedeemPostResponse = RedeemMagicLinkAuthMagicRedeemPostResponses[keyof RedeemMagicLinkAuthMagicRedeemPostResponses];

export type RequestMagicLinkAuthMagicRequestPostData = {
    body: MagicRequest;
    path?: never;
    query?: never;
    url: '/auth/magic/request';
};

export type RequestMagicLinkAuthMagicRequestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestMagicLinkAuthMagicRequestPostError = RequestMagicLinkAuthMagicRequestPostErrors[keyof RequestMagicLinkAuthMagicRequestPostErrors];

export type RequestMagicLinkAuthMagicRequestPostResponses = {
    /**
     * Response Request Magic Link Auth Magic Request Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type RequestMagicLinkAuthMagicRequestPostResponse = RequestMagicLinkAuthMagicRequestPostResponses[keyof RequestMagicLinkAuthMagicRequestPostResponses];

export type AuthMeAuthMeGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthMeAuthMeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthMeAuthMeGetError = AuthMeAuthMeGetErrors[keyof AuthMeAuthMeGetErrors];

export type AuthMeAuthMeGetResponses = {
    /**
     * Response Auth Me Auth Me Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AuthMeAuthMeGetResponse = AuthMeAuthMeGetResponses[keyof AuthMeAuthMeGetResponses];

export type RefreshSessionAuthRefreshPostData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type RefreshSessionAuthRefreshPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshSessionAuthRefreshPostError = RefreshSessionAuthRefreshPostErrors[keyof RefreshSessionAuthRefreshPostErrors];

export type RefreshSessionAuthRefreshPostResponses = {
    /**
     * Successful Response
     */
    200: RefreshResponse;
};

export type RefreshSessionAuthRefreshPostResponse = RefreshSessionAuthRefreshPostResponses[keyof RefreshSessionAuthRefreshPostResponses];

export type StartOutboundCallCallsOutboundPostData = {
    body: OutboundCallRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/calls/outbound';
};

export type StartOutboundCallCallsOutboundPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartOutboundCallCallsOutboundPostError = StartOutboundCallCallsOutboundPostErrors[keyof StartOutboundCallCallsOutboundPostErrors];

export type StartOutboundCallCallsOutboundPostResponses = {
    /**
     * Successful Response
     */
    202: OutboundCallResult;
};

export type StartOutboundCallCallsOutboundPostResponse = StartOutboundCallCallsOutboundPostResponses[keyof StartOutboundCallCallsOutboundPostResponses];

export type GetCallRecordCallsCallIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Call Id
         */
        call_id: string;
    };
    query?: never;
    url: '/calls/{call_id}';
};

export type GetCallRecordCallsCallIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetCallRecordCallsCallIdGetError = GetCallRecordCallsCallIdGetErrors[keyof GetCallRecordCallsCallIdGetErrors];

export type GetCallRecordCallsCallIdGetResponses = {
    /**
     * Successful Response
     */
    200: CallRecord;
};

export type GetCallRecordCallsCallIdGetResponse = GetCallRecordCallsCallIdGetResponses[keyof GetCallRecordCallsCallIdGetResponses];

export type SearchContactsContactsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/contacts';
};

export type SearchContactsContactsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchContactsContactsGetError = SearchContactsContactsGetErrors[keyof SearchContactsContactsGetErrors];

export type SearchContactsContactsGetResponses = {
    /**
     * Response Search Contacts Contacts Get
     *
     * Successful Response
     */
    200: Array<Contact>;
};

export type SearchContactsContactsGetResponse = SearchContactsContactsGetResponses[keyof SearchContactsContactsGetResponses];

export type GetContactContactsContactIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Contact Id
         */
        contact_id: string;
    };
    query?: never;
    url: '/contacts/{contact_id}';
};

export type GetContactContactsContactIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContactContactsContactIdGetError = GetContactContactsContactIdGetErrors[keyof GetContactContactsContactIdGetErrors];

export type GetContactContactsContactIdGetResponses = {
    /**
     * Successful Response
     */
    200: Contact;
};

export type GetContactContactsContactIdGetResponse = GetContactContactsContactIdGetResponses[keyof GetContactContactsContactIdGetResponses];

export type SeedDemoDataDemoSeedPostData = {
    /**
     * Body
     */
    body?: SeedRequest | null;
    path?: never;
    query?: never;
    url: '/demo/seed';
};

export type SeedDemoDataDemoSeedPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SeedDemoDataDemoSeedPostError = SeedDemoDataDemoSeedPostErrors[keyof SeedDemoDataDemoSeedPostErrors];

export type SeedDemoDataDemoSeedPostResponses = {
    /**
     * Successful Response
     */
    200: SeedResult;
};

export type SeedDemoDataDemoSeedPostResponse = SeedDemoDataDemoSeedPostResponses[keyof SeedDemoDataDemoSeedPostResponses];

export type ListFeedbackFeedbackGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Listing Key
         */
        listing_key: string;
    };
    url: '/feedback';
};

export type ListFeedbackFeedbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFeedbackFeedbackGetError = ListFeedbackFeedbackGetErrors[keyof ListFeedbackFeedbackGetErrors];

export type ListFeedbackFeedbackGetResponses = {
    /**
     * Response List Feedback Feedback Get
     *
     * Successful Response
     */
    200: Array<ShowingFeedback>;
};

export type ListFeedbackFeedbackGetResponse = ListFeedbackFeedbackGetResponses[keyof ListFeedbackFeedbackGetResponses];

export type ListFilesFilesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query: {
        /**
         * Folder
         */
        folder: string;
    };
    url: '/files';
};

export type ListFilesFilesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFilesFilesGetError = ListFilesFilesGetErrors[keyof ListFilesFilesGetErrors];

export type ListFilesFilesGetResponses = {
    /**
     * Response List Files Files Get
     *
     * Successful Response
     */
    200: Array<FileRef>;
};

export type ListFilesFilesGetResponse = ListFilesFilesGetResponses[keyof ListFilesFilesGetResponses];

export type HealthzHealthzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzHealthzGetResponses = {
    /**
     * Response Healthz Healthz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthzHealthzGetResponse = HealthzHealthzGetResponses[keyof HealthzHealthzGetResponses];

export type RunMilestoneChecksInternalCronMilestonesPostData = {
    body?: never;
    headers?: {
        /**
         * X-Cron-Key
         */
        'x-cron-key'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/internal/cron/milestones';
};

export type RunMilestoneChecksInternalCronMilestonesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunMilestoneChecksInternalCronMilestonesPostError = RunMilestoneChecksInternalCronMilestonesPostErrors[keyof RunMilestoneChecksInternalCronMilestonesPostErrors];

export type RunMilestoneChecksInternalCronMilestonesPostResponses = {
    /**
     * Response Run Milestone Checks Internal Cron Milestones Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RunMilestoneChecksInternalCronMilestonesPostResponse = RunMilestoneChecksInternalCronMilestonesPostResponses[keyof RunMilestoneChecksInternalCronMilestonesPostResponses];

export type SearchListingsListingsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: ListingStatus | null;
        /**
         * City
         */
        city?: string | null;
        /**
         * Min Price
         */
        min_price?: number | null;
        /**
         * Max Price
         */
        max_price?: number | null;
        /**
         * Min Bedrooms
         */
        min_bedrooms?: number | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/listings';
};

export type SearchListingsListingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchListingsListingsGetError = SearchListingsListingsGetErrors[keyof SearchListingsListingsGetErrors];

export type SearchListingsListingsGetResponses = {
    /**
     * Response Search Listings Listings Get
     *
     * Successful Response
     */
    200: Array<Listing>;
};

export type SearchListingsListingsGetResponse = SearchListingsListingsGetResponses[keyof SearchListingsListingsGetResponses];

export type GetListingListingsListingKeyGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Listing Key
         */
        listing_key: string;
    };
    query?: never;
    url: '/listings/{listing_key}';
};

export type GetListingListingsListingKeyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetListingListingsListingKeyGetError = GetListingListingsListingKeyGetErrors[keyof GetListingListingsListingKeyGetErrors];

export type GetListingListingsListingKeyGetResponses = {
    /**
     * Successful Response
     */
    200: Listing;
};

export type GetListingListingsListingKeyGetResponse = GetListingListingsListingKeyGetResponses[keyof GetListingListingsListingKeyGetResponses];

export type ListMessagesMessagesGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Contact Id
         */
        contact_id?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/messages';
};

export type ListMessagesMessagesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListMessagesMessagesGetError = ListMessagesMessagesGetErrors[keyof ListMessagesMessagesGetErrors];

export type ListMessagesMessagesGetResponses = {
    /**
     * Response List Messages Messages Get
     *
     * Successful Response
     */
    200: Array<Message>;
};

export type ListMessagesMessagesGetResponse = ListMessagesMessagesGetResponses[keyof ListMessagesMessagesGetResponses];

export type SendMessageMessagesSendPostData = {
    body: SendMessageRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/messages/send';
};

export type SendMessageMessagesSendPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SendMessageMessagesSendPostError = SendMessageMessagesSendPostErrors[keyof SendMessageMessagesSendPostErrors];

export type SendMessageMessagesSendPostResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type SendMessageMessagesSendPostResponse = SendMessageMessagesSendPostResponses[keyof SendMessageMessagesSendPostResponses];

export type GetMessageMessagesMessageIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/messages/{message_id}';
};

export type GetMessageMessagesMessageIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMessageMessagesMessageIdGetError = GetMessageMessagesMessageIdGetErrors[keyof GetMessageMessagesMessageIdGetErrors];

export type GetMessageMessagesMessageIdGetResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type GetMessageMessagesMessageIdGetResponse = GetMessageMessagesMessageIdGetResponses[keyof GetMessageMessagesMessageIdGetResponses];

export type RetryFailedMessageMessagesMessageIdRetryPostData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/messages/{message_id}/retry';
};

export type RetryFailedMessageMessagesMessageIdRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryFailedMessageMessagesMessageIdRetryPostError = RetryFailedMessageMessagesMessageIdRetryPostErrors[keyof RetryFailedMessageMessagesMessageIdRetryPostErrors];

export type RetryFailedMessageMessagesMessageIdRetryPostResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RetryFailedMessageMessagesMessageIdRetryPostResponse = RetryFailedMessageMessagesMessageIdRetryPostResponses[keyof RetryFailedMessageMessagesMessageIdRetryPostResponses];

export type ReadyzReadyzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzReadyzGetResponses = {
    /**
     * Response Readyz Readyz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadyzReadyzGetResponse = ReadyzReadyzGetResponses[keyof ReadyzReadyzGetResponses];

export type ListTransactionsTransactionsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/transactions';
};

export type ListTransactionsTransactionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTransactionsTransactionsGetError = ListTransactionsTransactionsGetErrors[keyof ListTransactionsTransactionsGetErrors];

export type ListTransactionsTransactionsGetResponses = {
    /**
     * Response List Transactions Transactions Get
     *
     * Successful Response
     */
    200: Array<TransactionDetail>;
};

export type ListTransactionsTransactionsGetResponse = ListTransactionsTransactionsGetResponses[keyof ListTransactionsTransactionsGetResponses];

export type OpenTransactionTransactionsPostData = {
    body: OpenTransaction;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/transactions';
};

export type OpenTransactionTransactionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OpenTransactionTransactionsPostError = OpenTransactionTransactionsPostErrors[keyof OpenTransactionTransactionsPostErrors];

export type OpenTransactionTransactionsPostResponses = {
    /**
     * Successful Response
     */
    201: TransactionDetail;
};

export type OpenTransactionTransactionsPostResponse = OpenTransactionTransactionsPostResponses[keyof OpenTransactionTransactionsPostResponses];

export type GetTransactionTransactionsTransactionIdGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Transaction Id
         */
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}';
};

export type GetTransactionTransactionsTransactionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTransactionTransactionsTransactionIdGetError = GetTransactionTransactionsTransactionIdGetErrors[keyof GetTransactionTransactionsTransactionIdGetErrors];

export type GetTransactionTransactionsTransactionIdGetResponses = {
    /**
     * Successful Response
     */
    200: TransactionDetail;
};

export type GetTransactionTransactionsTransactionIdGetResponse = GetTransactionTransactionsTransactionIdGetResponses[keyof GetTransactionTransactionsTransactionIdGetResponses];

export type ListDocumentsTransactionsTransactionIdDocumentsGetData = {
    body?: never;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Transaction Id
         */
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}/documents';
};

export type ListDocumentsTransactionsTransactionIdDocumentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentsTransactionsTransactionIdDocumentsGetError = ListDocumentsTransactionsTransactionIdDocumentsGetErrors[keyof ListDocumentsTransactionsTransactionIdDocumentsGetErrors];

export type ListDocumentsTransactionsTransactionIdDocumentsGetResponses = {
    /**
     * Response List Documents Transactions  Transaction Id  Documents Get
     *
     * Successful Response
     */
    200: Array<Document>;
};

export type ListDocumentsTransactionsTransactionIdDocumentsGetResponse = ListDocumentsTransactionsTransactionIdDocumentsGetResponses[keyof ListDocumentsTransactionsTransactionIdDocumentsGetResponses];

export type AttachDocumentTransactionsTransactionIdDocumentsPostData = {
    body: AttachDocument;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Transaction Id
         */
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}/documents';
};

export type AttachDocumentTransactionsTransactionIdDocumentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AttachDocumentTransactionsTransactionIdDocumentsPostError = AttachDocumentTransactionsTransactionIdDocumentsPostErrors[keyof AttachDocumentTransactionsTransactionIdDocumentsPostErrors];

export type AttachDocumentTransactionsTransactionIdDocumentsPostResponses = {
    /**
     * Successful Response
     */
    201: Document;
};

export type AttachDocumentTransactionsTransactionIdDocumentsPostResponse = AttachDocumentTransactionsTransactionIdDocumentsPostResponses[keyof AttachDocumentTransactionsTransactionIdDocumentsPostResponses];

export type UploadDocumentTransactionsTransactionIdDocumentsUploadPostData = {
    body: UploadDocument;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path: {
        /**
         * Transaction Id
         */
        transaction_id: string;
    };
    query?: never;
    url: '/transactions/{transaction_id}/documents/upload';
};

export type UploadDocumentTransactionsTransactionIdDocumentsUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadDocumentTransactionsTransactionIdDocumentsUploadPostError = UploadDocumentTransactionsTransactionIdDocumentsUploadPostErrors[keyof UploadDocumentTransactionsTransactionIdDocumentsUploadPostErrors];

export type UploadDocumentTransactionsTransactionIdDocumentsUploadPostResponses = {
    /**
     * Successful Response
     */
    201: Document;
};

export type UploadDocumentTransactionsTransactionIdDocumentsUploadPostResponse = UploadDocumentTransactionsTransactionIdDocumentsUploadPostResponses[keyof UploadDocumentTransactionsTransactionIdDocumentsUploadPostResponses];

export type TwilioSmsWebhookWebhooksTwilioSmsPostData = {
    body?: never;
    headers?: {
        /**
         * X-Twilio-Signature
         */
        'x-twilio-signature'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/webhooks/twilio-sms';
};

export type TwilioSmsWebhookWebhooksTwilioSmsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TwilioSmsWebhookWebhooksTwilioSmsPostError = TwilioSmsWebhookWebhooksTwilioSmsPostErrors[keyof TwilioSmsWebhookWebhooksTwilioSmsPostErrors];

export type TwilioSmsWebhookWebhooksTwilioSmsPostResponses = {
    /**
     * Response Twilio Sms Webhook Webhooks Twilio Sms Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type TwilioSmsWebhookWebhooksTwilioSmsPostResponse = TwilioSmsWebhookWebhooksTwilioSmsPostResponses[keyof TwilioSmsWebhookWebhooksTwilioSmsPostResponses];

export type VapiWebhookWebhooksVapiPostData = {
    body?: never;
    headers?: {
        /**
         * X-Vapi-Secret
         */
        'x-vapi-secret'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/webhooks/vapi';
};

export type VapiWebhookWebhooksVapiPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VapiWebhookWebhooksVapiPostError = VapiWebhookWebhooksVapiPostErrors[keyof VapiWebhookWebhooksVapiPostErrors];

export type VapiWebhookWebhooksVapiPostResponses = {
    /**
     * Response Vapi Webhook Webhooks Vapi Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type VapiWebhookWebhooksVapiPostResponse = VapiWebhookWebhooksVapiPostResponses[keyof VapiWebhookWebhooksVapiPostResponses];

export type StartListingToContractWorkflowsListingToContractStartPostData = {
    body: StartListingToContract;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/workflows/listing-to-contract/start';
};

export type StartListingToContractWorkflowsListingToContractStartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartListingToContractWorkflowsListingToContractStartPostError = StartListingToContractWorkflowsListingToContractStartPostErrors[keyof StartListingToContractWorkflowsListingToContractStartPostErrors];

export type StartListingToContractWorkflowsListingToContractStartPostResponses = {
    /**
     * Successful Response
     */
    202: WorkflowRunResult;
};

export type StartListingToContractWorkflowsListingToContractStartPostResponse = StartListingToContractWorkflowsListingToContractStartPostResponses[keyof StartListingToContractWorkflowsListingToContractStartPostResponses];
